sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t jrlong703/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jrlong703/docker-react npm run test
